
version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        image: frt/d2_db
        container_name: d2_db
        volumes:
             - ./db/sql:/docker-entrypoint-initdb.d
             - ./db/data:/var/lib/mysql
             #- ./db/my.cnf:/etc/mysql/conf.d/my.cnf

    crawl:
        build:
            context: .
            dockerfile: ./crawl/Dockerfile
        image: frt/d2_crawl
        container_name: d2_crawl
        
    analytics:
        build:
            context: .
            dockerfile: ./analytics/Dockerfile
        image: frt/d2_analytics
        container_name: d2_analytics
        ports:
            - 127.0.0.1:8888:8888
        volumes:
            - ./analytics/src:/mnt
